// Generated by https://quicktype.io

export interface Izapas {
    codigo:      string;
    name:        string;
    modelo:      string;
    precio:      string;
    foto:        string;
    descripcion: string;
    marca:       string;
    talla:       string;
    color:       string;
}
